# Default initial positions for MizukiArm_withDT35_3's ros2_control fake system

initial_positions:
  elbow_joint: 0
  forearm_root_joint: 0
  forearm_tip_joint: 0
  shoulder_pitch: 0
  wrist_joint: 0
