default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1
joint_limits:
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 2.0
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
  forearm_root_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 2.0
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
  forearm_tip_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 2.0
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
  shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 2.0
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
  wrist_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 2.0
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
