# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_pitch
      - elbow_joint
      - forearm_root_joint
      - forearm_tip_joint
      - wrist_joint