# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    # - hand_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - Slider 1
      - Revolute 2
      - Slider 4
      - Slider 5
  # hand_controller:
  #   type: FollowJointTrajectory
  #   action_ns: follow_joint_trajectory
  #   joints:
  #     - Slider 5