<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>nhk_launch</name>
  <version>0.0.1</version>
  <description>Bringup launch package for NHK robot workflow.</description>
  <maintainer email="a@todo.todo">a</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>

  <exec_depend>a_r2_trajectory_viz</exec_depend>
  <exec_depend>r2_odrive</exec_depend>
  <exec_depend>rogidrive</exec_depend>
  <exec_depend>rogilink_flex_gui</exec_depend>
  <exec_depend>nhk_bt</exec_depend>

  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
