default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1
joint_limits:
  "Revolute 1":
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 2.0
    has_position_limits: false
  "Revolute 2":
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 2.0
    has_position_limits: true
    min_position: -1.570796
    max_position: 1.570796
  "Revolute 3":
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 2.0
    has_position_limits: true
    min_position: -1.570796
    max_position: 1.570796
  "Revolute 4":
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 2.0
    has_position_limits: false
  "Revolute 5":
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 2.0
    has_position_limits: true
    min_position: -1.570796
    max_position: 1.570796
  "Revolute 6":
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 2.0
    has_position_limits: false
